### ISSUE TITLE
Windows XP 64 bit will show this error

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ex0days#2]
App will not lunch on WIN XP 64 bit , as i see this is a 64 Bit exe and it wont work on 23 bit 86x

The procedure entry point CancelIoEx could not be located in the dynamic link library KERNEL32.dll

any idea ? how to get it to run or fix this issue ?

thank you

**Comment by mbruel** [comment]
For 32 bit version that's normal! I compiled in 64 bit ;)

I can compile for 32bit if you want. But I don't have the compression tools, you'll have to give them to me. I need, Unrar.exe 32 bit (you can get it with WinRar 32bit), unace.exe (you can get it via Cygwin 32 bit, please take also cygwin1.dll) and then arj.exe (not sure where to find it...

About XP 64 bit... Who is still having XP? lol
I don't know which version of Qt is compatible with XP...

**Comment by mbruel** [comment]
sound like [Qt 5.5 works on XP](https://wiki.qt.io/PlatformSupport)...
but who still has XP?
I guess I could install a 32bit VM and compile it there but is there the need?...

**Comment by DEVUVO** [comment]
Yes sir , please try to get it to work for xp 64 bit and win 32 bit yes , I use XP , on vm and on old computer when some old applications dont run on win 10 they works in win xp :)

you might need to make a LINUX AND MAC OSX  too like ngpost , this app will rock you will see .

**Comment by mbruel** [comment]
I spent few hours trying to install XP then firefox to finally be able to download Qt v5.5.1.
It doesn't seem to work anymore. I got this error: `The procedure entry point strnlen could not be located in dynamic link library msvcrt.dll`
So it is dead I guess for XP. I won't loose more time. You can try on your side if you want. It's pretty easy to compile. I couldn't install cygwin neither on XP...

I'm going to close this issue. Please open another one for the win32 release.
As I said, please provide me arj.exe (32 bit) and unace.exe with cygwin1.dll (for this you need to install Cygwin 32bit and select unace, maybe take p7zip from there too, maybe there won't be this issue of 7z on amd). and finally unrar.exe from winrar 32bit.
Cheers

**Comment by mbruel** [comment]
> you might need to make a LINUX AND MAC OSX too like ngpost , this app will rock you will see .

on Linux and Mac, people can build the app themselves I suppose...
+ those kind of 0days were mainly on windows no?

**Comment by mbruel** [comment]
I finally managed to build on XP 32bit.
This version should work on ANY version of Windows.  I guess I'll stick to that one. No need to have a 64bit version.
[Here it is](https://files.fm/f/29d3em9u), let me know if it is working so I can make the proper release.
Cheers

PS: for Linux and Mac, people can build it. I don't have any Mac so I can't do it.
