### ISSUE TITLE
A single good rar marked as bad because its name

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ex0days#3]
after test many folders i find out that i have many single rars inside a single zip ends up with numbers sometimes there is 2 or 3 complete rar set have a numbers before the filetype 

example
the program will report a good single rar or 2 parts of rar it as missing  the first part according to the .999 
so here is the deal
if the file format are .999 this means it does start with .001 because its a split file
if the files i have are 
ABCDEFG.999.rar then this is not a part of rar set this is a full file because there is no .part before the number and there is .rar after the number

a part file from new winrar will look like this
 ABCDEFG.part999.rar

so if there is no .part before the number then this is a split file will be like this  .999 for example 

if there is only dot before the numbers and no .rar after the number then this is a split file too

so here is the different

ABCDEFG.999.rar  this is just one rar file = first part of the set if found
ABCDEFG.999.r00 and so on

ABCDEFG.999 this is a split file . there is no part before the number and no .rar after the number

ABCDEFG.PART999.rar this is a part of winrar set 

thats all , thank you.

**Comment by mbruel** [comment]
Should be fixed. [Try on this version](https://files.fm/f/29d3em9u) and let me know.

**Comment by DEVUVO** [comment]
All good.
